my_string=input('Напишите три произвольных слова через пробел: ')
print('Количество символов написанной строки: ',len(my_string))
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(' ',''))
print(my_string[0:1])
print(my_string[-1])